# Generated by Django 2.2 on 2020-07-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20200624_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='budget',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
